# Generated by Django 5.2.11 on 2026-03-03 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 3, 9, 1, 45, 263797, tzinfo=datetime.timezone.utc), verbose_name='published date'),
        ),
    ]
